#!/usr/bin/env python3
"""Watch a running arm and resume it from its last checkpoint if it dies.

    scripts/resume_guard.py --exp experiments/ccpo-attncred-150-20260913
    scripts/resume_guard.py --exp <dir> --dry-run     # report, never launch

WHY THIS IS NOT `trainer.resume_mode=auto`. `auto` silently continues whatever
checkpoint happens to sit in the run's directory, which turns a rerun of a named arm
into an undeclared continuation (see scripts/exp_run.py). This guard resumes only a
run it watched die, names the checkpoint explicitly, and records every decision in
outputs/guard.log, so a resumed arm is always traceable.

LIVENESS IS READ FROM THE LOG, NOT THE PID. A training run launched by a different
shell can sit in a different PID namespace -- `kill -0 <train.pid>` reports "dead"
for a run that is demonstrably alive. train.log mtime is namespace-independent, so
the guard treats "log has not advanced for --stale seconds" as death. That is a
heuristic: --stale defaults to 45 minutes, roughly 3x the slowest step this project
has measured (896 s), and a run that is merely slow will not trip it.

WHAT A RESUME COSTS. On resume the trainer burns one env reset per completed step to
realign the training game draw, plus the validation-draw burn (see
ACG_ALIGN_TRAIN_ON_RESUME / ACG_ALIGN_VAL_ON_RESUME in ray_trainer.py). Both are
needed for the resumed run to be comparable to a fresh one at matched steps. Resuming
at step 100 therefore costs ~100 + ~40 resets before the first training step.

Up to `save_freq` steps of work are lost per resume; the estimator state is not
checkpointed, but it is rebuilt per batch, so nothing estimator-side carries over.
"""

import argparse
import datetime
import json
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def log(exp_dir, msg):
    line = f"[{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(os.path.join(exp_dir, "outputs", "guard.log"), "a") as fh:
        fh.write(line + "\n")


def last_step(exp_dir):
    """Steps completed, from the metrics the trainer appends one row per step."""
    p = os.path.join(exp_dir, "outputs", "metrics.jsonl")
    if not os.path.exists(p):
        return 0
    with open(p) as fh:
        return sum(1 for _ in fh)


def checkpoint_step(exp_dir):
    """The last COMPLETE checkpoint.

    verl writes latest_checkpointed_iteration.txt after the actor and the dataloader
    are on disk (ray_trainer.py:_save_checkpoint), so the marker never names a partial
    save. Never pick the highest-numbered global_step_* directory instead -- that one
    may be a save that was interrupted.
    """
    p = os.path.join(exp_dir, "outputs", "checkpoints", "latest_checkpointed_iteration.txt")
    if not os.path.exists(p):
        return None
    try:
        n = int(open(p).read().strip())
    except ValueError:
        return None
    d = os.path.join(exp_dir, "outputs", "checkpoints", f"global_step_{n}")
    return (n, d) if os.path.isdir(d) else None


def log_age(exp_dir):
    p = os.path.join(exp_dir, "outputs", "train.log")
    if not os.path.exists(p):
        return None
    return time.time() - os.path.getmtime(p)


def build_resume_script(exp_dir, ckpt_dir):
    """Derive a resume command from run.sh, which exp_run.py regenerates from config.json.

    Only the resume flags are rewritten, so every other knob stays byte-identical to
    the launch that produced the checkpoint -- the condition for a resume to be a
    continuation of anything.
    """
    run_sh = os.path.join(exp_dir, "run.sh")
    body = open(run_sh).read()
    if "trainer.resume_mode=" not in body:
        return None
    body = re.sub(r"trainer\.resume_mode=\S+", "trainer.resume_mode=resume_path", body)
    body = re.sub(r"\s*\\\n\s*trainer\.resume_from_path=\S+", "", body)
    body = body.replace(
        "trainer.resume_mode=resume_path",
        f"trainer.resume_mode=resume_path \\\n  trainer.resume_from_path={ckpt_dir}",
        1,
    )
    body = body.replace(
        "# Regenerated from config.json by scripts/exp_run.py -- do not hand-edit.",
        "# Generated by scripts/resume_guard.py from run.sh -- do not hand-edit.",
        1,
    )
    out = os.path.join(exp_dir, "outputs", "resume.sh")
    with open(out, "w") as fh:
        fh.write(body)
    os.chmod(out, 0o755)
    return out


def relaunch(exp_dir, script):
    train_log = os.path.join(exp_dir, "outputs", "train.log")
    with open(train_log, "ab", buffering=0) as fh:
        fh.write(f"\n=== resumed by resume_guard at "
                 f"{datetime.datetime.now().isoformat(timespec='seconds')} ===\n".encode())
        p = subprocess.Popen(["bash", script], cwd=os.path.join(ROOT, "verl-agent"),
                             stdout=fh, stderr=subprocess.STDOUT, start_new_session=True)
    with open(os.path.join(exp_dir, "outputs", "train.pid"), "w") as fh:
        fh.write(str(p.pid))
    return p.pid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp", required=True, help="experiment directory")
    ap.add_argument("--stale", type=int, default=2700,
                    help="seconds without a train.log write before the run counts as dead "
                         "(default 2700 = 45 min, ~3x the slowest measured step)")
    ap.add_argument("--poll", type=int, default=120, help="seconds between checks")
    ap.add_argument("--max-retries", type=int, default=3)
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would happen; never launch")
    a = ap.parse_args()

    exp_dir = a.exp if os.path.isabs(a.exp) else os.path.join(ROOT, a.exp)
    if not os.path.isdir(exp_dir):
        sys.exit(f"no such experiment directory: {exp_dir}")
    os.makedirs(os.path.join(exp_dir, "outputs"), exist_ok=True)

    # exp_run.py nests the resolved arm config under "config"; everything else in
    # config.json is provenance (git sha, versions, hydra overrides).
    cfg = json.load(open(os.path.join(exp_dir, "config.json"))).get("config", {})
    total = int(cfg.get("total_epochs", 0))
    if not total:
        sys.exit("config.json has no config.total_epochs; refusing to guard a run "
                 "whose finish line is unknown")
    log(exp_dir, f"guard watching {os.path.basename(exp_dir)}: target {total} steps, "
                 f"stale={a.stale}s poll={a.poll}s max_retries={a.max_retries}"
                 + (" [DRY RUN]" if a.dry_run else ""))

    retries = 0
    last_resume_step = None
    while True:
        done = last_step(exp_dir)
        if total and done >= total:
            log(exp_dir, f"run finished: {done}/{total} steps. guard exiting.")
            return 0

        age = log_age(exp_dir)
        if age is None:
            log(exp_dir, "no train.log yet; waiting")
        elif age < a.stale:
            pass  # alive
        else:
            log(exp_dir, f"train.log has not advanced for {age / 60:.0f} min "
                         f"(threshold {a.stale / 60:.0f}); run looks dead at step {done}/{total}")
            ck = checkpoint_step(exp_dir)
            if ck is None:
                log(exp_dir, "no complete checkpoint to resume from. guard exiting -- "
                             "this run has to be restarted from scratch.")
                return 1
            step, ckpt_dir = ck
            if last_resume_step is not None and step <= last_resume_step:
                log(exp_dir, f"checkpoint still at step {step} after the last resume: "
                             f"the run is not making progress. guard exiting rather than "
                             f"looping.")
                return 1
            if retries >= a.max_retries:
                log(exp_dir, f"already resumed {retries} times; giving up.")
                return 1

            lost = done - step
            log(exp_dir, f"resuming from step {step} ({ckpt_dir}); "
                         f"{lost} completed step(s) will be re-run")
            script = build_resume_script(exp_dir, ckpt_dir)
            if script is None:
                log(exp_dir, "could not derive a resume command from run.sh. guard exiting.")
                return 1
            if a.dry_run:
                log(exp_dir, f"[DRY RUN] would launch: bash {script}")
                return 0
            pid = relaunch(exp_dir, script)
            retries += 1
            last_resume_step = step
            log(exp_dir, f"relaunched as pid {pid} (retry {retries}/{a.max_retries}); "
                         f"the trainer will burn ~{step} training and "
                         f"~{step // max(int(cfg.get('test_freq', 5)), 1)} validation resets "
                         f"to realign both draws")
            time.sleep(max(a.poll, 300))  # give it room to start before judging it again

        time.sleep(a.poll)


if __name__ == "__main__":
    sys.exit(main())
